console.log('Root element:', document.documentElement);
console.log('Body element:', document.body);
console.log('Head element:', document.head);
console.log('Document title:', document.title);
console.log('Document URL:', document.URL);
console.log('Document domain:', document.domain);
console.log('Referring document:', document.referrer);
console.log('Document cookies:', document.cookie);
console.log('Forms in the document:', document.forms);
console.log('Document Character Set : ',document.characterSet);
console.log('Images in the document:', document.images);
console.log('Links in the document:', document.links);
console.log('Scripts in the document:', document.scripts);
console.log('Style sheets in the document:', document.styleSheets);
console.log('Default view (window):', document.defaultView);
console.log('Document ready state:', document.readyState);
console.log('Root element language:', document.documentElement.lang);
