image: node

cache:
  paths:
    - node_modules/

stages:
  - setup
  - build
  - dev

setup-pnpm:
  stage: setup
  script:
    - node -v && npm -v
    - npm install -g pnpm@9.0.0
    - pnpm -v

build-node19:
  stage: build
  script:
    - npx pnpm install
    - npx pnpm run build
  artifacts:
    paths:
      - node_modules/

build-node18:
  stage: build
  script:
    - npx pnpm install
    - npx pnpm run build
  artifacts:
    paths:
      - node_modules/

build-node20:
  stage: build
  script:
    - npx pnpm install
    - npx pnpm run build
  artifacts:
    paths:
      - node_modules/

build-node21:
  stage: build
  script:
    - npx pnpm install
    - npx pnpm run build
  artifacts:
    paths:
      - node_modules/

build-node22:
  stage: build
  script:
    - npx pnpm install
    - npx pnpm run build
  artifacts:
    paths:
      - node_modules/

development:
  stage: dev
  script:
    - echo "Executing Project With pnpm."
    - sleep 3
    - npm start
