name: "✍️ ​ ​Missing or Deprecated Topics"
description: Help us improve the content by suggesting changes
labels: [enhancement]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help us improve with your suggestions.
  - type: input
    id: url
    attributes:
      label: URL
      description: Please provide the URL of the topic you are suggesting changes to.
      placeholder: https://github.com/offensive-vk/UntilEverything/
    validations:
      required: true
  - type: textarea
    id: suggestions
    attributes:
      label: Suggestions
      description: What changes would you like to suggest?
      placeholder: Enter your suggestions here.
    validations:
      required: true