name: CI / Automated PR

on:
  push:
    branches-ignore:
      - "master"
      - "old"
      - "main"
      - "2023"
      - "nov-2023"
      - "specialized-commits"
  workflow_dispatch:

jobs:
  create_pr:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' && github.event.pusher.name != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v4

      - name: Create or Update Pull Request
        id: create-pr
        uses: offensive-vk/auto-pr-action@master
        with:
          repo-token: ${{ secrets.BOT_TOKEN }}
          destination_branch: "master"
          title: "Hamster Left A Pull Request - (${{ github.event.head_commit.message }})"
          body: "### Hamster is working here. Sit Tight !"
          reviewers: "offensive-vk"
          labels: "hamster"
          assignees: "TheHamsterBot"
          draft: false
          debug: true

      - name: Save PR Number in ENV
        run: echo "PR_NUMBER=${{ steps.create-pr.outputs.number }}" >> $GITHUB_ENV

  update_pr:
    needs: create_pr
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' && github.event.pusher.name != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v4

      - name: Generate Pull Request Template
        run: |
          timestamp=$(date '+%b %d, %A %I:%M:%S %p')
          markdown=$(cat <<EOF
          ### This Pull Request Was Automated by [Hamster [bot]](https://github.com/TheHamsterBot)

          > [!NOTE]
          > Workflow Trigger: ${{ github.event_name }} event ${{ github.ref_name }}
          > Details of Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

          - Author: @TheHamsterBot
          - Branch: master (base) / ${{ github.ref_name }} (head)
          - Commit: ${{ github.sha }}
          - Workflow Path: ${{ github.workflow }}
          - Pusher Details: ${{ github.event.pusher.name }} - <${{ github.event.pusher.email }}>

          ---
          
          Thanks.
          $timestamp
          Your Hamster 🐹 <code>PF78VAPPKLZ2</code>
          EOF)
          echo "$markdown" > .github/Auto_Pull_Request.md
          echo "MARKDOWN<<EOF" >> $GITHUB_ENV
          echo "$markdown" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update Pull Request Body
        run: |
          gh pr edit "$PR_NUMBER" --body "$MARKDOWN"
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
