name: CI / Automated Docker Commands

on:
  workflow_dispatch:
    inputs:
      repeat_count:
        description: "Number of Times"
        required: true
        default: 10
        type: number

jobs:
  images:
    runs-on: ubuntu-latest
    name: Automate Stuff
    services:
      docker:
        image: docker:dind
        options: >-
          --privileged  --mount
          type=tmpfs,destination=/var/lib/docker,tmpfs-size=4096m
        ports:
          - 2375:2375
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Run Commands
      run: |
        for i in $(seq 1 ${{ github.event.inputs.repeat_count }}); do
            docker pull ntsystems/untileverything:latest
            docker rmi ntsystems/untileverything:latest
            docker pull ghcr.io/offensive-vk/untileverything:latest
            docker rmi ghcr.io/offensive-vk/untileverything:latest
            docker system prune -f 
        done
